### ISSUE TITLE
[Feature request] User can specify files to be processed as a subset of files to be read ?

### ISSUE THREAD

**Issue by jmmonnet** [r-lidar/lasR#1]
Would it be possible to specify files to be read but only a subset to be processed, e.g. by making `lasR` able to consider the `$processed` attribute in a lidR `LAScatalog` object ? This would allow the user to make sure that processed files are free of edge artefacts, which is not the case for border tiles in case all files are processed.

**Comment by Jean-Romain** [comment]
I started working on it and I reshaped a bit the code internally so I can handle this in a close future.

**Comment by Jean-Romain** [comment]
The feature has been added in 0.2.0 available in the `devel` branch. It only works with a `LAScatalog` from `lidR`.
