### ISSUE TITLE
`keep_random_fraction` filter enhancement

### ISSUE THREAD

**Issue by georgewoolsey** [r-lidar/lasR#102]
Prior to `lasR 0.13.0` the use of the `LASlib` filter `-keep_random_fraction` was accessible to enable decimation of points in a pipeline. Would it be possible to add a lasR filter to decimate points in a way similar to the `LASlib` filter `-keep_random_fraction` without exposing the point cloud to R as in the workaround example below?

```r
# random fraction of points for decimate
  rand_frac <- "0.2"

# # OLD: used to be able to pass the filter: "-keep_class 2 -keep_random_fraction 0.2"
# # NEW: keep_random_fraction not available in lasR 0.13.0 filtering
  tri_filter <- c( "Classification == 2", paste0("RAND<=", rand_frac) )

# add RAND to extra bytes, but requires exposing data to R
  fun <- function(data) { data$RAND <- sample(1:nrow(data)) / nrow(data); return(data) }
  add_rand <- lasR::add_extrabytes("uint64", "RAND", "Random sample") +
    lasR::callback(fun, expose = "xyz")

# use the filter in triangulate
  tri <- lasR::triangulate(filter = tri_filter)

# dtm
  dtm <- lasR::rasterize(res = 1, operators = tri)

# pipeline
  p <- lasR::reader() + add_rand + tri + dtm

# execute
  f <- system.file("extdata", "MixedConifer.laz", package = "lidR")
  ans <- lasR::exec(p, on = f)
```

**Comment by georgewoolsey** [comment]
I think your `sampling_pixel()` solution should work for my supplied use case which would make the `keep_random_fraction` filter a lower priority.

However, I am currently getting the following error when I try to use the `sampling_pixel()` stage as a filter in the `triangulate()` stage:

```
Error in validate_filter(x[["filter"]], allow_laslib_filter) : 
   Condition list(algoname = "sampling_pixel", res = 0.5, filter = "Classification == 2", method = "min",
   use_attribute = "Z", shuffle_size = 2147483647, uid = "10153ad0", output = "") not recognized.
```

I am using `lasR_0.13.0` on `R version 4.3.0` running under Windows 10 x64

Example code with error occurring when defining the `triangulate()` stage

```r
# using conditional filter
resample_gnd <- lasR::sampling_pixel(res = 0.5, method = "min", filter = "Classification == 2")
tri <- lasR::triangulate(filter = resample_gnd) # ERROR
# using lasR filter
resample_gnd <- lasR::sampling_pixel(res = 0.5, method = "min", filter = lasR::keep_ground())
tri <- lasR::triangulate(filter = resample_gnd) # ERROR
```

**Comment by Jean-Romain** [comment]
Ok I'll fix it. Should not be a big deal.

**Comment by Jean-Romain** [comment]
`filter` is expecting a **string**. You have 2 **stages**

```r
resample_gnd <- lasR::sampling_pixel(res = 0.5, method = "min", filter = lasR::keep_ground())
tri <- lasR::triangulate(filter ="") 
pipeline = resample_gnd + tri
```

**Comment by Jean-Romain** [comment]
Some explanation maybe.

In first stage you are asking `lasR`: resample the point cloud but you will work only with ground points. Thus the point cloud is mainly left intact and ground point only are resampled (you have less ground points)

In second stage you are asking `lasR`: triangulate the point cloud but you will work only with ground points. But in the previous stage you removed numerous ground point so it has less ground point to process.

**Comment by georgewoolsey** [comment]
That makes sense, thanks for the extra explanation. I was not clear on the behavior of `sampling_pixel()` that the *non-ground points would remain intact* for use in later pipeline stages.

This solution works for the supplied use case, please feel free to de-prioritize the `keep_random_fraction` filter. Point decimation of ground points for triangulation is related to working with high-density point clouds as mentioned in 
#18 .

Here is the full example of what I am using the point cloud decimation of ground points for showing that the non-ground point density is not significantly reduced in the final, normalized point cloud after applying the `sampling_pixel()` stage:

```r
# classify
c <- lasR::classify_with_csf() + lasR::classify_with_ivf()
# resample ground
resample_gnd <- lasR::sampling_pixel(res = 0.1, method = "min", filter = lasR::keep_ground())
# triangulate with reduced density ground points
tri <- lasR::triangulate(filter = lasR::keep_ground())
# dtm
dtm <- lasR::rasterize(res = 0.5, operators = tri)
# normalize
norm <- lasR::transform_with(stage = dtm, operator = "-")
# pipeline
pipeline <- lasR::reader() + c + lasR::summarise() + resample_gnd + tri + dtm + norm + lasR::summarise()
# exec
f <- system.file("extdata", "Megaplot.laz", package = "lidR")
ans <- lasR::exec(pipeline, on = f)
ans[["summary"]][["npoints_per_class"]]
ans[["summary.1"]][["npoints_per_class"]]
```

**Comment by Jean-Romain** [comment]
> Here is the full example of what I am using the point cloud decimation of ground points for showing that the non-ground point density is not significantly reduced in the final,

You are using the Megaplot.laz. A special low density point cloud custom decimated to take the minimum amount of disk memory to respect storage CRAN policy. You tried to retain one ground point per 10 cm pixel which, in this very specific case, is almost equivalent to keeping all ground points.

**Comment by georgewoolsey** [comment]
> You are using the Megaplot.laz file. A special low density point cloud custom decimated to take the minimum amount of disk memory to respect storage CRAN policy. You tried to retain one ground point per 10 cm pixel which, in this very specific case, is almost equivalent to keeping all ground points.

For completeness, below is the result using the high density point cloud mentioned in #18 from Sherwood et al. (2018) accessible [here](https://www.sciencebase.gov/catalog/item/5b1ee160e4b092d965254a60). The result of `sampling_pixel()` is as desired with the non-ground points intact for use in later pipeline stages and the ground points decimated to improve the processing time of  the `triangulate()` stage.

```r
# original classified point cloud
ans[["summary"]][["npoints_per_class"]]
```
```
       0        2 
48406655 32742774 
```
after applying `sampling_pixel()`

```r
# normalized point cloud with ground points resampled
ans[["summary.1"]][["npoints_per_class"]]
```
```
       0        2 
48400877  5160646
```

**Comment by Jean-Romain** [comment]
48406655/48400877 there is an unexplained difference of 5778 points. Weird.

**Comment by georgewoolsey** [comment]
The loss of non-ground points happens when the point cloud is normalized using `lasR::transform_with(stage = dtm, operator = "-")` . Probably the non-exact nature of normalizing with a rasterized DTM.

The loss of non-ground points does not occur directly after the `sampling_pixel()` stage as in the pipeline

```r
# classify
c <- lasR::classify_with_csf() + lasR::classify_with_ivf()
# resample ground
resample_gnd <- lasR::sampling_pixel(res = 0.1, method = "min", filter = lasR::keep_ground())
# pipeline
pipeline <- lasR::reader() + c + lasR::summarise() + resample_gnd + lasR::summarise()
# exec
ans <- lasR::exec(pipeline, on = f)
```
```r
# original classified point cloud
ans[["summary"]][["npoints_per_class"]]
       0        2 
48406655 32742774 
```
after applying sampling_pixel() *but before normalization with DTM raster*
```r
# point cloud with ground points resampled
ans[["summary.1"]][["npoints_per_class"]]
       0        2 
48406655  5161188 
```

**Comment by georgewoolsey** [comment]
As always, thank you for your prompt response and excellent insight on this matter

**Comment by Jean-Romain** [comment]
Ho I see. This is the points that are outside the convex hull of the ground points on the edges.
