### ISSUE TITLE
Cannot install version 0.4.0

### ISSUE THREAD

**Issue by kalinowskapatrycja** [r-lidar/lasR#19]
I get the following compilation error when trying to update to the new version:
[error_log.txt](https://github.com/r-lidar/lasR/files/14816379/error_log.txt)

Previous versions compiled and ran fine.

**Comment by Jean-Romain** [comment]
Ok, the error makes sense despite `lasR 0.4.0` was tested on Windows with success. I pushed a fix. It should work now but cannot confirm since it was already working here on github continuous integration

**Comment by kalinowskapatrycja** [comment]
It works now. 

Thank you..
