### ISSUE TITLE
Error when writing tree segmentation to disk 

### ISSUE THREAD

**Issue by wiesehahn** [r-lidar/lasR#28]
I wanted to write results of region growing to disk with e.g.

```r
f <- system.file("extdata", "MixedConifer.las", package="lasR")

reader <- reader_las(filter = keep_first())
chm <- rasterize(1, "max")
lmx <- local_maximum_raster(chm, 5)
tree <- region_growing(chm, lmx, max_cr = 10, ofile = "test.gpkg")
u <- exec(reader + chm + lmx + tree, on = f)

```
when I get an error

```
 The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.
``` 

despite the message a geopackage file is written, but I expected that a vector data file of tree segmentation is written, instead its raster. 

There is no definition of possible output formats under [region_growing()](https://r-lidar.github.io/lasR/reference/region_growing.html)

In my first attempt on an own file I also got 

```
Warning 3: Cannot find tms_NZTM2000.json (GDAL_DATA is not defined)`)
```

**Comment by Jean-Romain** [comment]
`region_growing` produces a raster. Rasters can indeed be written in geopackage files and `test.gpkg` is likely valid (I tested and QGIS read it). Yet, at the very end of `exec` the `.gpkg` files are read with `sf` and `sf` fails at reading a raster. `terra` can read your file. However, in my code, the choice for `terra::rast` vs. `sf::st_read` is based on file extension.

This could be improved (I did not envisaged your use case) but will be low in my priority list.
