### ISSUE TITLE
Problem when using filter in rasterize()

### ISSUE THREAD

**Issue by wiesehahn** [r-lidar/lasR#29]
When I try to calculate to calculate some rasterized metric with a filter I get strange results, where some areas (small tiles), get no value or wrong values. Its less pronounced with the testdata but it looks weird to me as well.

```r
f <- system.file("extdata", "Topography.las", package="lasR")

imean <- rasterize(2, "imean")
pipeline = imean
ans = exec(pipeline, on = f)

imean <- rasterize(2, "imean", filter = drop_class(2))
pipeline = imean
ans = exec(pipeline, on = f)
```

without filter:
![grafik](https://github.com/r-lidar/lasR/assets/41429613/1cda2194-7de4-4db2-b36a-f3cdeda643c1)

with filter:
![grafik](https://github.com/r-lidar/lasR/assets/41429613/5194cb45-2997-485b-9798-2bed2d24f208)

E.g. with the filter I would not expext that the area in the lower left changes, since we are dropping ground points but this area is water.

**Comment by wiesehahn** [comment]
> By the way in this specific case you should prefer my version of the pipeline. It reads and load less points, implies less computation and should be faster and more memory efficient. Yet, your code is correct and should work.

But if I want to calculate multiple metrics, e.g. DTM, CHM and imean filering in initial read is not an option I guess. Would you suggest to do this separate then or is it more effective to do it in a pipeline like `pipeline = dtm + norm + chm + imean` ?

**Comment by Jean-Romain** [comment]
Absolutely not. In the more complex pipeline you are describing, your use case is the correct way to do it. I was just signaling the information for this specific simple pipeline just in case it may help.

**Comment by Jean-Romain** [comment]
Fixed. 

Fun fact: there was a comment on the problematic line of code with something like: `//TODO: check if this line is correct`.
