### ISSUE TITLE
possibly wrong code in plot-inventory tutorial

### ISSUE THREAD

**Issue by wiesehahn** [r-lidar/lasR#61]
wow, 0.6.0 seems like a big update, especially with the metrics engine 👍 

I was just quickly reading through the tutorial and havent tested it but the https://r-lidar.github.io/lasR/articles/tutorial.html#plot-inventory pipeline seems wrong to me. 

Shouldnt it be something like this?
```r
read <- reader_las(xc = xcenter, yc = ycenter, r = 11.28) 
tri <- triangulate(filter = keep_ground())
norm <- transform_with(tri)
metrics <- summarise(metrics = c("z_mean", "z_p95", "i_median", "count"))
write1 <- write_las(ofiles_plot)
write2 <- write_las(ofiles_plot_norm)

pipeline = read + write1 + norm + metrics + write2
```

**Comment by Jean-Romain** [comment]
There was a error but not the one you are suggesting. In your pipeline `tri` is not in the pipeline ans thus it will fail when constructing the pipeline because `transform_with` cannot connect to `tri` which is missing.


```r
read <- reader_las(xc = xcenter, yc = ycenter, r = 11.28) 
tri <- triangulate(filter = keep_ground())
trans <- transform_with(tri)
norm <- tri + trans
metrics <- summarise(metrics = c("z_mean", "z_p95", "i_median", "count"))
write1 <- write_las(ofiles_plot)
write2 <- write_las(ofiles_plot_norm)
```
