### ISSUE TITLE
Search bar on https://r-lidar.github.io/lasR/ does not work.

### ISSUE THREAD

**Issue by harryseely** [r-lidar/lasR#94]
The search bar on the [lasR reference website](https://r-lidar.github.io/lasR/) does not work and returns the error pasted below.

Of course this is not an essential feature, but since many methods are spread across several vignettes, it would be helpful to have a functional search bar.

Thanks!

```404
There isn't a GitHub Pages site here.

If you're trying to publish one, [read the full documentation](https://help.github.com/pages/) to learn how to set up GitHub Pages for your repository, organization, or user account.```

**Comment by Jean-Romain** [comment]
The link is not working. You may have been unlucky and found a temporary bug on Github.

**Comment by kadyb** [comment]
@Jean-Romain

https://github.com/r-lidar/lasR/blob/37b07d56462e25ea7b63a802497a16f83aa57776/_pkgdown.yml#L1

Change this line to `url: https://r-lidar.github.io/lasR/` and it should work.

**Comment by Jean-Romain** [comment]
Nice. Thank you for the tip
