### ISSUE TITLE
exec pipeline stopped working

### ISSUE THREAD

**Issue by summitbri** [r-lidar/lasR#96]
I've been using lasR for some time now, thank you for the great work! 

Just recently my system simply stops while executing any pipelines.  Not sure if this is related to the 0.12 release or R 4.4.2.

This is a relatively small .las file, one of several I've tried.  The pipeline simply stops after reading the header.  Any suggestions on how to troubleshoot?

> f <- "T:/_TESTPOINTCLOUDS/cloud3.las"
> read <- reader_las()
> pipeline <- read + summarise()
> ans <- exec(pipeline, on = f)
Read files headers: [==========] 100% (1 threads)

**Comment by summitbri** [comment]
Quick update, exec pipeline seems to be working fine on Ubuntu, just not either of my 2 Windows 11 machines under both an older and most recent version of R and RStudio.

Ubuntu 24.04.1 LTS: R version 4.3.3 (works)
Windows 11 machine 1: R version 4.4.1, RStudio 2024.04.2 (doesn't work)
Windows 11 machine 2: R version 4.4.2, RStudio 2024.09.1 (doesn't work)

**Comment by Jean-Romain** [comment]
Well, is passes all the unit test https://github.com/r-lidar/lasR/actions/runs/11919268809. Please try to reinstall. I made some mess when pushing 0.12.  Finger crossed.

**Comment by summitbri** [comment]
Unfortunately, same result.

**Comment by Jean-Romain** [comment]
Well that sucks. I will investigate on my virtual machine.

**Comment by Jean-Romain** [comment]
Tested on windows with 4.3.3. Everything looks fine. All units tests are passing in a normal time frame.  I suggest you to get back to 10.1 waiting for a fix. Another user reported that it pipeline is taking 4 hours instead of 3 minutes. Weird.

```r
remotes::install_github("r-lidr/lasR", ref = "ab345f0")
```

**Comment by summitbri** [comment]
Well I'm glad it wasn't just me missing something obvious.  Working in Ubuntu now so I'll circle back to Windows later.  Thanks!

**Comment by Jean-Romain** [comment]
It should be fixed now. Binaries should be available within an hour on r-universe. You can install from GitHub right now.

**Comment by summitbri** [comment]
Thanks for the quick fix!

**Comment by summitbri** [comment]
Seems to be working!  Thanks again.
